#!bin/bash

echo "———————————————————————————————————————————"
echo "Script to swap the gievn numbers and strings"
echo "———————————————————————————————————————————"
echo "a=\c"; read a
echo "b=\c"; read b
echo "——————————————————————"
echo "After swapping..."
echo "——————————————————————"
sleep 20
echo "a=$b"
echo "b=$a"
echo "———————————————————————————————————————————"
